MISTRAL_API_KEY = "LWVhbj9GfrDyjmM9gOWfNsgBp1vbnG2y"
PINECONE_API_KEY = "2317fa27-9998-49a3-99df-72fc11c10ad4"
HF_TOKEN = "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"
LANGCHAIN_API_KEY = "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"